# Generated by Django 5.0.3 on 2024-03-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('P50', models.DecimalField(decimal_places=25, max_digits=30)),
                ('P100', models.DecimalField(decimal_places=25, max_digits=30)),
                ('P250', models.DecimalField(decimal_places=25, max_digits=30)),
                ('P500', models.DecimalField(decimal_places=25, max_digits=30)),
                ('P1000', models.DecimalField(decimal_places=25, max_digits=30)),
            ],
        ),
    ]
